// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace ObjectifLune
{
	public class Server
	{
		public Server() { 
			var appServer = new SuperWebSocket.WebSocketServer();
			
			//Setup the appServer
			if (!appServer.Setup(60600)) //Setup with listening port
			{
				Console.WriteLine("Failed to setup!");
				Console.ReadKey();
				return;
			}
		}
	}
}

